### ISSUE TITLE
Dynamically activating gnus-outlook-style (to enable switching between reply styles)

### ISSUE THREAD

**Issue by mgalgs** [lokedhs/gnus-outlook-style#5]
I currently use the code below to allow for choosing a different cite reply style every time I reply.  As far as I can tell, `gnus-outlook-style` seems to hijack a lot of the `gnus` infrastructure with advice and whatnot, and I couldn't figure out a clean way of disabling it for some replies but not others.  Is there any way for me to choose dynamically whether I want to use `gnus-outlook-style` or something else?

```elisp
(defun my-set-style-traditional ()
  (interactive)
  (my-set-cite-reply-position 'traditional))

(defun my-set-style-above ()
  (interactive)
  (my-set-cite-reply-position 'above))

(defun my-set-style-below ()
  (interactive)
  (my-set-cite-reply-position 'below))

(setq my-reply-style-one-key-menu-alist
      '((("t" . "Traditional") . my-set-style-traditional)
        (("a" . "Above") . my-set-style-above)
        (("b" . "Below") . my-set-style-below)))

(setq gnus-posting-styles
      '((".*"
         (signature "Mitch")
         (eval (one-key-menu "reply" my-reply-style-one-key-menu-alist t)))))
```

**Comment by lokedhs** [comment]
That's interesting and indeed useful. I haven't thought about doing such
thing because I only use Gnus for my work-related mail. I don't have time
to look into this any time soon but if you want to give it a shot the
change should go into the function outlook-style--gnus-prepare. If the
content of this function is never run, then any other actions of this
package will be suppressed. So, all you would have to do is to check for
the reply styles in this function (or better: a function that surrounds it).

**Comment by mgalgs** [comment]
Awesome, let me give this a shot.
